import React, { useState } from 'react';
import AIDetectionResult from './AIDetectionResult';
import './AIOnlyCheck.css';

function AIOnlyCheck({ onResult }) {
  const [text, setText] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);

  const handleCheck = async () => {
    if (!text.trim()) {
      alert('Please enter text to check');
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const { checkAIOnly } = require('../api/api');
      const response = await checkAIOnly({ text });
      setResult(response.data);
      if (onResult) {
        onResult(response.data);
      }
    } catch (error) {
      alert('Error checking AI content: ' + (error.response?.data?.detail || error.message));
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setResult(null);
    setText('');
  };

  return (
    <div className="ai-only-check">
      <div className="ai-only-header">
        <h2>🤖 AI Content Detection</h2>
        <p className="ai-only-description">
          Analyze your text to determine if it was generated by AI tools like ChatGPT, GPT-4, 
          or other language models. Our detector identifies common AI writing patterns, 
          sentence structures, and linguistic markers.
        </p>
      </div>

      {!result ? (
        <div className="ai-only-input-section">
          <label>Enter Text to Analyze</label>
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Paste or type your text here to check if it was AI-generated..."
            rows="15"
            className="ai-only-textarea"
          />
          
          <div className="ai-only-info">
            <div className="info-grid">
              <div className="info-card">
                <div className="info-icon">🎯</div>
                <h4>What We Detect</h4>
                <ul>
                  <li>Common AI phrases and patterns</li>
                  <li>Sentence structure uniformity</li>
                  <li>Perplexity and predictability</li>
                  <li>Writing style consistency</li>
                </ul>
              </div>
              <div className="info-card">
                <div className="info-icon">📊</div>
                <h4>Analysis Metrics</h4>
                <ul>
                  <li>AI Probability Score (0-100%)</li>
                  <li>Confidence Level (High/Medium/Low)</li>
                  <li>Detected AI Patterns</li>
                  <li>Detailed Statistical Analysis</li>
                </ul>
              </div>
              <div className="info-card">
                <div className="info-icon">💡</div>
                <h4>Best Results</h4>
                <ul>
                  <li>Minimum 50 words recommended</li>
                  <li>Complete sentences work best</li>
                  <li>Context-rich text is more accurate</li>
                  <li>Longer texts = better accuracy</li>
                </ul>
              </div>
            </div>
          </div>

          <button 
            onClick={handleCheck} 
            className="btn-primary btn-ai-check" 
            disabled={loading || !text.trim()}
          >
            {loading ? (
              <>
                <span className="spinner-small"></span>
                Analyzing Content...
              </>
            ) : (
              <>🤖 Analyze AI Content</>
            )}
          </button>
        </div>
      ) : (
        <div className="ai-only-results">
          <div className="ai-only-result-header">
            <h3>AI Detection Results</h3>
            <button onClick={handleReset} className="btn-secondary">
              Check Another Text
            </button>
          </div>

          {/* Display AI Detection Results */}
          <AIDetectionResult aiResult={result.ai_detection} />
          
          {/* Additional Info */}
          <div className="ai-disclaimer">
            <h4>⚠️ Important Notes:</h4>
            <ul>
              <li>This is a probabilistic analysis, not a definitive judgment</li>
              <li>Results should be considered alongside other evidence</li>
              <li>Human-written text can sometimes show AI-like patterns</li>
              <li>AI-generated text may be edited to appear more human</li>
              <li>Use this tool as part of a comprehensive content review process</li>
            </ul>
          </div>
        </div>
      )}
    </div>
  );
}

export default AIOnlyCheck;